---
title: "Building the Womens CenSoc File"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Building the Womens CenSoc File}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# Overview 
This document will briefly outline steps to build the women's CenSoc file. All source code can be found at: github.com/caseybreen/wcensoc


## Library Packages
```{r, eval = F}
library(data.table)
library(wcensoc)
```

## Create and Clean SS-5 Death Files
```{r, eval = F}
## Run script to clean SS-5 Death Files
ss5_death <- load_numdeath()

## Run Script to add geography onto SS-5 Death Files   
ss5_death <- load_numdeath_geo(numdeath = ss5_death)
```

## Create, Clean, and Condense SS-5 Application File
```{r, eval = F}
ss5_application <- load_numapp()

## Selects the "best" sex, race, dob, etc. from the ss5 application file.
## This takes a very long time to run (~ 8 hours)
ss5_application <- condense_numapp(numapp = ss5_application)
```

## Merge the SS-5 Application File with the SS-5 Death File
```{r, eval = F}
ss5 <- merge_numapp_numdeath(numapp_condensed = ss5_application, numdeath = ss5_death)
```

## Load Census File

```{r, eval = F}
census <- load_census(census_file = "../../IPUMS/1940/CSV/P.csv")
```

## Merge SS-5 and Census Files on linking keys

```{r, eval = F}
wcensoc <- census_ss5_merge(ss5 = ss5, census = census)
```

