---
title: "CenSoc Users"
author: Casey Breen
---

Summary: This code tracks the total number of CenSoc users. Specifically, it reads in a log of all people who have signed up to download CenSoc data. Next, it creates parses download-log files from the website. 

```{r}
library(tidyverse)
library(lubridate)
library(ApacheLogProcessor)
library(stringr)
library(cowplot)
```


## Download Sign-up Logs 

```{r}
## censoc download sqlite DBI

path.to.db <- "/admin/lab_writeable/Censoc1313/Sqdata/crusers.db"  # not renamed from Creles project

tmp.db <- tempfile()

# user needs to own file or something, otherwise it is locked. So make a copy
system( paste0("cp -a ",  path.to.db, " ", tmp.db ) )

#RSQlite is used
  library(DBI)
  library(RSQLite)

  db <- dbConnect(SQLite(), tmp.db ,  flags = SQLITE_RO, synchronous = NULL)

  dbListTables(db)
  signup_log <- dbGetQuery(db, "SELECT * from users LIMIT 1000000")  # records are transactions, not unique users
  dbGetQuery(db, "SELECT COUNT(*) from users")

  # DBI returns data.frames
  str( dbGetQuery(db, "SELECT * from users LIMIT 10") )

  dbDisconnect(db)
  
## Filter to dates after our first release (April 1st, 2020)
  
users <- signup_log %>% 
  mutate(date = as_date(dateh)) %>% 
  filter(date > "2020-04-01") %>% 
  arrange(desc(date))

## New users
users <- users %>% 
  mutate(fname = tools::toTitleCase(tolower(fname)),
         lname = tools::toTitleCase(tolower(lname))) %>% 
  group_by(fname, lname) %>% 
  arrange(date) %>% 
  filter(row_number() == 1)

```

```{r}
## number of new users by month
users %>% 
  group_by(month = lubridate::floor_date(date, "month")) %>%
  tally()

## number of new users
users %>% group_by(date) %>% 
  tally() %>% 
  mutate(source = "New Signup",
         total = cumsum(n)) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = total), size = 1, color = "black") + 
  theme_cowplot() + 
  labs(y = "Users",
       x = "Date",
       title = "Total CenSoc Users")
```

## Parse String Logs from Website

```{r}
## Parse Strings 
censocLogs <- read.multiple.apache.access.log("/admin/lab_writeable/Censoc1313/Weblogs/",
prefix="censoc-access.log")

download_logs <- censocLogs %>% 
  filter(httpcode == 200) %>% 
  filter(str_detect(url, pattern = "GET /Data/"))

download_logs <- download_logs %>% 
  mutate(dataset_downloaded = case_when(
    str_detect(url, pattern = "bunmd_v1") == TRUE ~ "BUNMD_V1",
    str_detect(url, pattern = "bunmd_v2") == TRUE ~ "BUNMD_V2",
    str_detect(url, pattern = "numident_v1") == TRUE ~ "CenSoc-Numident_V1",
    str_detect(url, pattern = "numident_v2") == TRUE ~ "CenSoc-Numident_V2",
    str_detect(url, pattern = "numident_demo") == TRUE ~ "CenSoc-Numident Demo",
    str_detect(url, pattern = "dmf_v1") == TRUE ~ "CenSoc-DMF_V1",
    str_detect(url, pattern = "dmf_v2") == TRUE ~ "CenSoc-DMF_V2",
    str_detect(url, pattern = "dmf_demo") == TRUE ~ "CenSoc-DMF Demo",
    TRUE ~ NA_character_
  )) %>% 
  mutate(url2 = url) %>% 
  separate(url, c(NA, NA, "link"), sep = "/") %>% 
  mutate(link = tolower(link))
```

## Create a list of all downloads
```{r}
## all downloads 
signup_log <- signup_log %>% 
  mutate(link = tolower(link))

## combine all signups with all download logs
censoc_downloaders <- download_logs %>% 
  left_join(signup_log) 

## Create wide dataset
censoc_downloaders <- censoc_downloaders %>% 
  group_by(fname, lname, dataset_downloaded) %>% 
  filter(row_number() == 1) %>% 
  dplyr::select(fname, lname, email, dataset_downloaded, dateh) %>% 
  ungroup()

all_downloads <- censoc_downloaders %>% 
  filter(!is.na(dataset_downloaded)) %>% 
  mutate(download = 1) %>% 
  pivot_wider(id_cols = c(fname, lname, email),
              names_from = dataset_downloaded, 
              values_from = download)

## combine with original user file
users <- users %>% 
  left_join(all_downloads %>% 
              select(-fname, -lname), by = ("email")) %>% 
  select(-datetm, -dateh, -link)

users_new <- users %>% 
  filter(date >= as_date("2021-02-10"))

```

## Visualize 

```{r}
## new signups over time
new_signups <- signup_log %>% 
  mutate(date = as_date(dateh)) %>% 
  filter(date > "2020-04-01") %>% 
  group_by(fname, lname) %>% 
  arrange(by(date)) %>% 
  filter(row_number() == 1) %>% 
  group_by(date) %>% 
  tally() %>% 
  mutate(source = "New Signup",
         total = cumsum(n))

new_signups %>% 
ggplot() + 
  geom_line(aes(x = date, y = total), size = 1, color = "black") + 
  theme_light(base_size = 30) + 
  labs(y = "Users",
       x = "Date",
       title = "CenSoc Users (New)")+ 
  ylim(0, 220)
```


```{r}
## Downloads by dataset
downloads <- censoc_downloaders %>% 
  filter(!is.na(dataset_downloaded)) %>% 
  group_by(dataset_downloaded) %>% 
  tally()

downloads %>% 
  ggplot() + 
  geom_point(aes(x = reorder(dataset_downloaded, n), y = n), size = 7, color = "black") + 
  coord_flip() + 
  labs(x = "",                                                     
       y = "Downloads",
       title = "Downloads by Dataset") + 
  theme_light(base_size = 30) 
```




























