---
title: "Code Book For SS5"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Put the title of your vignette here}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

|   | Variable     | Label|
|--:|:-------------|:---------------------------------------------|
|  1|ssn           |Social Security Number                        |
|  2|fname         |First Name                                    |
|  2|fname_         |First Name                                    |
|  3|lname         |Last Name                                     |
|  4|sex           |Sex                                           |
|  5|byear         |Year of Birth                                 |
|  6|bmonth        |Month of Birth                                |
|  7|bday          |Day of Birth                                  |
|  8|dyear         |Year of Death                                 |
|  9|dmonth        |Month of Death                                |
| 10|dday          |Day of Death                                  |
| 11|census_age    |Age during 1940 Census                        |
| 12|zip_residence |ZIP code                                      |
| 13|socstate      |State where Social Security Number was Issued |
| 14|dcity         |City of Death                                 |
| 15|dstate        |State of Death                                |


\newpage 

**\huge{ssn}**
\normalsize
\vspace{12pt}

Label: Social Security Number

Description: ssn is 9-character value corresponding to Social Security number as recorded in the Social Security Num Death file. This variable uniquely identifies all records in the NumDeath dataset. 


\newpage 


**\huge{fname}**
\normalsize
\vspace{12pt}

Label: First Name

Description: fname is a character variable reporting the first name of an individual at the time of death as recorded in the Social Security Num Death file.

Note: First names have been cleaned to contain no spaces and no punctuation



\newpage 

**\huge{lname}**
\normalsize
\vspace{12pt}

Label: Last Name

Description: lname is a character variable reporting the last name of an individual at the time of death as recorded in the Social Security Num Death file.  


\newpage 

**\huge{sex}**
\normalsize
\vspace{12pt}

Label: Sex

Description: Sex is a numeric variable reporting the last name of an individual at the time of death. 

| Code|     Label    | Frequency| Percent |
|----:|-------------:|-------------:|-----:|
|  0  | Missing      |13759361 |27.9%|
|  1  | Men          | 17519143|35.5%|
|  2  | Women        | 17975996|36.5%|

\newpage 


**\huge{byear}**
\normalsize
\vspace{12pt}

Label: Year of Birth

Description: byear is the year of birth as reported to the Social Security Administration.

\newpage 


**\huge{bmonth}**
\normalsize
\vspace{12pt}

Label: Month of Birth

Description: bmonth is the month of birth as reported to the Social Security Administration.


\newpage 
