---
title: "R Notebook"
output: html_notebook
---

### Load Packages
```{r}
library(censoc)
library(tidyverse)
library(data.table)
```

Read in Social Security Death Master file, census file, and create censoc file 
```{r}
socsec_files = c("/home/ipums/josh-ipums/progs/ssdm/ssdm1",
                     "/home/ipums/josh-ipums/progs/ssdm/ssdm2",
                     "/home/ipums/josh-ipums/progs/ssdm/ssdm3")

socsec <- load_socsec_deaths(socsec_files)
census <- load_census(census_file = "/home/ipums/casey-ipums/IPUMS2019/1940/TSV/P.tsv")
censoc.dmf <- create_censoc(census, socsec)
```

Calculate age at death variables 
```{r}
censoc.dmf <- calculate_age_at_death(censoc.dmf)
```

Calculate weights
```{r}
censoc.dmf <- create_weights_dmf_link(censoc.dmf)
```

Optional: add household variables from census
```{r}
household_census <- fread("/home/ipums/casey-ipums/IPUMS2019/1940/TSV/H.tsv")
censoc.dmf <- add_household_variables(censoc.dmf = censoc.dmf, household_census = household_census)
```

Clean CenSoc File -- we'll add some stuff here. 
```{r}
censoc.dmf <- censoc.dmf %>% 
  filter(!nchar(fname) <= 1)
```

Write out CenSoc file with all variables
```{r}
fwrite(censoc.dmf, "/censoc/data/censoc_linked_with_census/1940/censoc_dmf_v1.csv")
```

Write out CenSoc with all variables
```{r}
censoc.dmf.web <- censoc.dmf %>% 
  select(HISTID, STATEFIP, census_age, byear, bmonth, bday, dyear, dmonth, dday, death_age, weight)

fwrite(censoc.dmf.web, "/censoc/data/censoc_files_for_website/censoc_dmf_v1.csv")
```

