---
title: "Assessing Match Quality"
author: "Casey Breen" 
---

Summary: Assessing match quality in the 1940 census. 

```{r}
## Library packages 
library(tidyverse)
library(data.table)
library(censocdev)
library(cowplot)
library(gt)
library(ipumsr)
library(here)
```


```{r}
## read in dmf 
dmf <- fread("/censoc/data/censoc_v2/censoc_dmf_v2.csv") %>% 
  janitor::clean_names()

## read in 1940 census 
census_1940 <- fread("/ipums-repo2019/1940/TSV/P.tsv", select = c("HISTID", "SERIALP", "AGE", "INCWAGE", "SEX", "EDUC", "RACE", "RELATE", "REGION", "MARST", "SEI")) %>% 
  janitor::clean_names()

## read in 1940 census household
census_1940_h <- fread("/ipums-repo2019/1940/TSV/H.tsv", select = c("SERIAL", "STATEFIP", "OWNERSHP", "URBAN", "REGION")) %>% 
  janitor::clean_names()


dmf_death_prop <- read_csv(here("vignettes/assess_match_quality/data/dmf_death_prop.csv")) %>% 
  mutate(age = 1940 - cohort) ## imprecise but OK
```

```{r}
## combine census 
census_1940_hh_vars <- census_1940 %>% 
  inner_join(census_1940_h, by = c("serialp" = "serial"))

## add on dmf  
census_1940_hh_vars <- census_1940_hh_vars %>% 
  left_join(dmf, by = "histid")

## drop sex 
census_1940_hh_vars <- census_1940_hh_vars %>% 
  filter(sex == 1)

## recode 
census_1940_hh_vars <- census_1940_hh_vars %>% 
  censocdev::recode_education(educ_var = educ)

## data dictionary initiative
ipums_ddi <- ipumsr::read_ipums_ddi("/ipums-repo2019-1/fullcount.ddi.xml")

census_1940_hh_vars <- census_1940_hh_vars %>% 
  janitor::clean_names(case = "all_caps") %>% 
  ipumsr::ipums_collect(ipums_ddi, var_attrs = c("val_labels", "var_label", "var_desc")) %>% 
    janitor::clean_names()
```

## Calculate match rate 

```{r}
## create variable indicating whether someone has been matched 
census_1940_hh_vars <- census_1940_hh_vars %>% 
  mutate(match_conservative = case_when(
    link_abe_exact_conservative == 1 ~ "Matched",
    TRUE ~ "Unmatched"
  ),
  match_standard = case_when(
    link_abe_exact_conservative %in% c(0, 1) ~ "Matched",
    TRUE ~ "Unmatched"
  ), 
  hs = case_when(
    educ >= 60 & educ < 998 ~ 1,
    TRUE ~ 0
  ), 
  rural = case_when(
    urban == 1 ~ 1,
    TRUE ~ 0
  ),
  black = case_when( 
    race == 200 ~ 1,
    TRUE ~ 0
  ), white = case_when(
    race == 100 ~ 1,
    TRUE ~ 0
  ),
  homeown = case_when(
    ownershp == 10 ~ 1, 
    TRUE ~ 0
  ),
  p_hh_head = case_when(
    relate == 101 ~ 1, 
    TRUE ~ 0
  ),
  p_hh_head = case_when(
    relate == 101 ~ 1, 
    TRUE ~ 0
  ),
  educ_level = case_when(
    educ <= 50 ~ "< High School",
    educ %in% 60:90 ~ "High School or some college",
    educ %in% 100 ~ "Bachelors Degree",
    educ %in% 110:116 ~ "Advanced Degree"
  ), 
  sei_recode = case_when(
    sei %in% 1:9 ~ "sei_1_9",
    sei %in% 10:14 ~ "sei_10_14",
    sei %in% 15:25 ~ "sei_15_25",
    sei >= 26 ~      "sei_26+"
  ),
  marital_status = case_when(
      marst %in% 1:2 ~ "married",
      TRUE ~ "not married" ),
  race_recode = case_when(
    race == 100 ~ "White",
    race == 200 ~ "Black",
    TRUE ~ "Other"
  ))
```

```{r}
## dmf match rate (standard)
match_rate <- census_1940_hh_vars %>% 
  group_by(age) %>% 
  summarize(match_rate = round(mean(match_standard == "Matched"), 3)) %>% 
  mutate(match_type = "standard")

match_rate <- match_rate %>% 
  left_join(dmf_death_prop, by = "age") %>% 
  mutate(match_rate_adusted = (1/prop_dying_5yr_smoothed) * match_rate)

## dmf match rate (conservative)
match_rate_conservative <- census_1940_hh_vars %>% 
  group_by(age) %>% 
  summarize(match_rate = round(mean(match_conservative == "Matched"), 3)) %>% 
  mutate(match_type = "conservative")

match_rate_conservative <- match_rate_conservative %>% 
  left_join(dmf_death_prop, by = "age") %>% 
  mutate(match_rate_adusted = (1/prop_dying_5yr_smoothed) * match_rate)

## plot dmf match rate 
dmf_match_rate <- match_rate %>% 
  bind_rows(match_rate_conservative) %>% 
  filter(cohort %in% c(1900:1935)) %>% 
  ggplot(aes(x = cohort, y = match_rate, color = match_type)) + 
  geom_line() + 
  geom_point() + 
  theme_cowplot() + 
  ggsci::scale_color_lancet() + 
  labs(x = "Birth Cohort",
       y = "Match Rate",
       title = "Raw Match Rate") + 
  ylim(0, .5) + 
  theme(legend.position = "bottom", legend.title = element_blank()) 


## plot dmf match rate 
dmf_match_rate_adjusted <- match_rate %>% 
  bind_rows(match_rate_conservative) %>% 
  filter(cohort %in% c(1900:1935)) %>% 
  ggplot(aes(x = cohort, y = match_rate_adusted, color = match_type)) + 
  geom_line() + 
  geom_point() + 
  theme_cowplot() + 
  ggsci::scale_color_lancet() + 
  labs(x = "Birth Cohort",
       y = "Match Rate",
       title = "Mortality-Adjusted Match Rate") + 
  ylim(0, .5) + 
  theme(legend.position = "bottom", legend.title = element_blank()) 


## combine into one plot 
dmf_match_rate_combined <- cowplot::plot_grid(dmf_match_rate, dmf_match_rate_adjusted, labels = "auto")

## save plot 
ggsave(dmf_match_rate_combined, filename = here("vignettes/assess_match_quality/figs/dmf_raw_match_rate.pdf"), height = 4, width = 10)
```

## Comparison of Socioeconomic Status 

```{r}
## Calculate sample proportion (standard)
characteristics_standard <- census_1940_hh_vars %>% 
  group_by(age, match_standard) %>%
  summarize(p_hs = mean(hs),
            p_rural = mean(rural),
            p_black = mean(black),
            p_white = mean(white),
            p_homeown = mean(homeown),
            p_household_head = mean(p_hh_head)) %>% 
  pivot_longer(cols = starts_with("p_"), names_to = "type",
               names_prefix = "p_", values_to = "prop")

## Calculate sample proportion (conservative)
matched_characteristics_conservative <- census_1940_hh_vars %>% 
  group_by(age, match_conservative) %>%
  summarize(p_hs = mean(hs),
            p_rural = mean(rural),
            p_black = mean(black),
            p_white = mean(white),
            p_homeown = mean(homeown),
            p_household_head = mean(p_hh_head)) %>% 
  pivot_longer(cols = starts_with("p_"), names_to = "type",
               names_prefix = "p_", values_to = "prop")

## Reshape data (standard)
matched_characteristics_standard <- matched_characteristics_standard %>% 
  mutate(type = as.factor(case_when(
    type == "hs" ~ "Educ: High School",
    type == "rural" ~ "Rural",
    type == "black" ~ "Race: Black",
    type == "white" ~ "Race: White",
    type == "household_head" ~ "Houshold Head",
    type == "homeown" ~ "Home Owner"
  ))) %>% 
  mutate(type = factor(type, levels=c('Educ: High School',
                                      'Race: Black','Race: White', 'Rural',
                                      "Houshold Head", "Home Owner"))) %>% 


## Reshape data (conservative)
matched_characteristics_conservative <- matched_characteristics_conservative %>% 
  mutate(type = as.factor(case_when(
    type == "hs" ~ "Educ: High School",
    type == "rural" ~ "Rural",
    type == "black" ~ "Race: Black",
    type == "white" ~ "Race: White",
    type == "household_head" ~ "Houshold Head",
    type == "homeown" ~ "Home Owner"
  ))) %>% 
  mutate(type = factor(type, levels=c('Educ: High School',
                                      'Race: Black','Race: White', 'Rural',
                                      "Houshold Head", "Home Owner")))




## Plot data —— DMF representativeness (standard)
matched_characteristics_plot_standard <- matched_characteristics_standard %>% 
   ggplot(aes(x = age, y = prop, color = as.factor(match_standard))) + 
  geom_line(size = 1) + 
  theme_cowplot() + 
  ggsci::scale_color_lancet() + 
  xlim(20, 50) + 
  theme(legend.position = "bottom", legend.title = element_blank()) + 
  facet_wrap(~type) + 
    background_grid() 

## Plot data —— DMF representativeness (conservative)
matched_characteristics_plot_conservative <- matched_characteristics_conservative %>% 
   ggplot(aes(x = age, y = prop, color = as.factor(match_conservative))) + 
  geom_line(size = 1) + 
  theme_cowplot() + 
  ggsci::scale_color_lancet() + 
  xlim(20, 50) + 
  theme(legend.position = "bottom", legend.title = element_blank()) + 
  facet_wrap(~type) + 
  background_grid() 


dmf_matched_characteristics_plot <- cowplot::plot_grid(matched_characteristics_plot_standard, matched_characteristics_plot_conservative, rows = 2) 


## save plot 
ggsave(matched_characteristics_plot_standard, filename = here("vignettes/assess_match_quality/figs/dmf_matched_characteristics_plot_standard.pdf"), height = 7, width = 10)

## save plot 
ggsave(matched_characteristics_plot_conservative, filename = here("vignettes/assess_match_quality/figs/dmf_matched_characteristics_plot_conservative.pdf"), height = 7, width = 10)
```

## Comparison of Socioeconomic Status 

```{r}
## Calculate sample proportion (unmatched)
unmatched_characteristics <- census_1940_hh_vars %>% 
  group_by(age) %>% 
  filter(match_standard == "Unmatched") %>% 
  summarize(p_hs = mean(hs),
            p_rural = mean(rural),
            p_black = mean(black),
            p_white = mean(white),
            p_homeown = mean(homeown),
            p_household_head = mean(p_hh_head)) %>% 
  pivot_longer(cols = starts_with("p_"), names_to = "type",
               names_prefix = "p_", values_to = "prop") %>% 
  mutate(category = "Unmatched")

## Calculate sample proportion (standard)
matched_characteristics_standard <- census_1940_hh_vars %>% 
  group_by(age) %>% 
  filter(match_standard == "Matched") %>% 
  summarize(p_hs = mean(hs),
            p_rural = mean(rural),
            p_black = mean(black),
            p_white = mean(white),
            p_homeown = mean(homeown),
            p_household_head = mean(p_hh_head)) %>% 
  pivot_longer(cols = starts_with("p_"), names_to = "type",
               names_prefix = "p_", values_to = "prop") %>% 
  mutate(category = "Matched (Standard)")

## Calculate sample proportion (conservative)
matched_characteristics_conservative <- census_1940_hh_vars %>% 
  group_by(age) %>% 
  filter(match_conservative == "Matched") %>% 
  summarize(p_hs = mean(hs),
            p_rural = mean(rural),
            p_black = mean(black),
            p_white = mean(white),
            p_homeown = mean(homeown),
            p_household_head = mean(p_hh_head)) %>% 
  pivot_longer(cols = starts_with("p_"), names_to = "type",
               names_prefix = "p_", values_to = "prop") %>% 
  mutate(category = "Matched (Conservative)")

## Rename vars for facets and set factor levels  
matched_characteristics_combined <- unmatched_characteristics %>% 
  bind_rows(matched_characteristics_standard) %>% 
  bind_rows(matched_characteristics_conservative) %>% 
  mutate(type = as.factor(case_when(
    type == "hs" ~ "Educ: High School",
    type == "rural" ~ "Rural",
    type == "black" ~ "Race: Black",
    type == "white" ~ "Race: White",
    type == "household_head" ~ "Houshold Head",
    type == "homeown" ~ "Home Owner"
  ))) %>% 
  mutate(type = factor(type, levels=c('Educ: High School',
                                      'Race: Black','Race: White', 'Rural',
                                      "Houshold Head", "Home Owner")))

## Plot data —— DMF representativeness (standard)
matched_characteristics_plot_standard <- matched_characteristics_combined %>% 
   ggplot(aes(x = age, y = prop, color = category)) + 
  geom_line(size = 1) + 
  theme_cowplot() + 
  ggsci::scale_color_lancet() + 
  xlim(20, 50) + 
  theme(legend.position = "bottom", legend.title = element_blank()) + 
  facet_wrap(~type) + 
  background_grid() + 
  labs(title = "CenSoc-DMF: Comparison of Socioeconomic Characteristics",
       y = "Proportion",
       x = "Age")

## save plot 
ggsave(matched_characteristics_plot_standard, filename = here("vignettes/assess_match_quality/figs/dmf_socioeconomic_characteristics.pdf"), height = 7, width = 10)

```


```{r}
## recode data  
 gen <- census_1940_hh_vars %>% 
  mutate(rural = case_when(
    rural == 1 ~ "Rural",
    TRUE ~ "Urban"
  ),
  homeown = case_when(
    homeown == 1 ~ "Home Owner",
    TRUE ~ "Not Home Owner"
  )) %>% 
  filter(age %in% 20:40) %>% 
  select(histid, race_recode, educ_level, sei_recode, marital_status, region_string, rural, homeown) %>%
  pivot_longer(-histid) %>% 
  group_by(name, value) %>%
  tally() %>%            
  mutate(prop = round(100*prop.table(n), 1)) %>% 
  rename(n_gen = n, prop_gen = prop)

censoc_dmf_1940_standard <- census_1940_hh_vars %>% 
  filter(link_abe_exact_standard == 1) %>% 
  mutate(rural = case_when(
    rural == 1 ~ "Rural",
    TRUE ~ "Urban"
  ),
  homeown = case_when(
    homeown == 1 ~ "Home Owner",
    TRUE ~ "Not Home Owner"
  )) %>% 
  filter(age %in% 20:40) %>% 
  select(histid, race_recode, educ_level, sei_recode, marital_status, region_string, rural, homeown) %>%
  pivot_longer(-histid) %>% 
  group_by(name, value) %>%
  tally() %>%            
  mutate(prop = round(100*prop.table(n), 1)) %>% 
  rename(n_gen_standard = n, prop_standard = prop)

censoc_dmf_1940_conservative <- census_1940_hh_vars %>% 
  filter(link_abe_exact_conservative == 1) %>% 
  mutate(rural = case_when(
    rural == 1 ~ "Rural",
    TRUE ~ "Urban"
  ),
  homeown = case_when(
    homeown == 1 ~ "Home Owner",
    TRUE ~ "Not Home Owner"
  )) %>% 
  filter(age %in% 20:40) %>% 
  select(histid, race_recode, educ_level, sei_recode, marital_status, region_string, rural, homeown) %>%
  pivot_longer(-histid) %>% 
  group_by(name, value) %>%
  tally() %>%            
  mutate(prop = round(100*prop.table(n), 1)) %>% 
  rename(n_gen_conservative = n, prop_conservative = prop)


unweighted_data <- gen %>% 
  inner_join(censoc_dmf_1940_standard, by = c("name", "value")) %>% 
  inner_join(censoc_dmf_1940_conservative, by = c("name", "value")) %>% 
 # mutate(name = as.factor(name), value = as.factor(name)) %>% 
  mutate(name = factor(name, levels = c("educ_level", "race_recode", "homeown", "sei_recode", "rural", "region_string", "Marital"))) %>% 
  # mutate(value = factor(value, levels = c('Male', 'Female',
  #                                     '18-29', '30-44', '45-59', '60+',
  #                                     '<HS Equivalent', "HS Equivalent", "Some college", "Bachelors", "Advanced degree",
  #                                     "White, non-Hispanic", "Black, non-Hispanic", "Other, non-Hispanic", "Hispanic", "2+, non-Hispanic", "Asian, non-Hispanic",
  #                                     "<$29,999", "$30,000 to $74,999", "$75,000 to $124,999", ">$125,000+",
  #                                     "Non-Metro Area", "Metro Area",
  #                                     "Married", "Widowed", "Divorced", "Separated", "Never married", "Living with partner"))) %>% 
  arrange(name, value) 

## create table 
table_s3 <- gt(data = unweighted_data) %>% 
  tab_spanner(
    label = "General Pop",
    columns = vars(
      n_gen, prop_gen)) %>% 
  tab_spanner(
    label = "Standard",
    columns = vars(
      n_gen_standard, prop_standard)) %>% 
  tab_spanner(
    label = "Conservative",
    columns = vars(
      n_gen_conservative, prop_conservative)) %>% 
  cols_label(
    "n_gen" = "No.",
    "prop_gen" = "%",
    "n_gen_standard" = "No.",
    "prop_standard" = "%",
    "n_gen_conservative"  = "No.",
    "prop_conservative" = "%",
    value = ""
  ) %>% 
  # row_group_order(
  #     groups = c("Gender", "Age", "Education", "Race")
  #   ) %>% 
  tab_style(
    style = list(
      cell_text(weight = "bold")),
    locations = cells_row_groups()
  ) %>% 
  opt_row_striping(row_striping = T) %>% 
  cols_align("left")


table_s3 %>%
  gtsave("dmf_characteristics_new.tex", path = here("vignettes/assess_match_quality/figs/")) 
```


```{r}
match_rate_characteristics <- census_1940_hh_vars %>% 
  mutate(rural = case_when(
    rural == 1 ~ "Rural",
    TRUE ~ "Urban"
  ),
  homeown = case_when(
    homeown == 1 ~ "Home Owner",
    TRUE ~ "Not Home Owner"
  )) %>% 
  filter(age %in% 20:40) %>% 
  select(histid, race_recode, educ_level, sei_recode, marital_status, region_string, rural, homeown) %>%
  pivot_longer(-c(histid, link_abe_exact_standard)) %>% 
  group_by(name, value) %>%
  summarize(mean(!is.na(link_abe_exact_standard)))
```


