---
title: "8-clean-civ-occupation-enlistment"
output: html_document
date: "2023-01-19"
---

```{r}
library(dplyr)   # %>%, group_by, tally, print
library(ipumsr)  # read_ipums_ddi, ipums_val_labels
library(readr)   # read_csv, write_csv
library(stringr) # str_trim, str_split
```

#NEED TO UPDATE PATH_TO_TEMP_DATA BEFORE FINAL RELEASE
```{r}
path_to_temp_data   <-  "/data/censoc/workspace/enlistment_records/temp7.csv"
out_path <- "/data/censoc/workspace/enlistment_records/"
civ_path <- "/data/censoc/input_data/enlistment_records_public/code/awenlistmentcode/cl_3323.csv" # to update
```

#READ IN TEMP 5-- UPDATE BEFORE FINAL RELEASE
```{r}

data_combined <- read_csv(path_to_temp_data, 
                          col_types = cols(
                            empty_field = col_character(),
                            term_or_enlistment = col_character(),
                            longevity = col_character(),
                            education = col_character(),
                            marital_status = col_character(),
                            component = col_character(),
                            educ_spec = col_character(),
                            defer_date_mmyy = col_character(),
                            mname_clean = col_character(),
                            sex = col_integer(),
                            sex_r = col_integer(),
                            fname_std = col_character()
                            )
                          )
```

```{r}
data_combined %>% 
  count(residence_state) 
```

```{r}
recode_res_state_enlistment <- function(df){
  
  ## recode source variable
  df <- df %>% 
    mutate(state_recode = case_when(
      residence_state == "41" ~ 41, #ALABAMA	
      residence_state == "D1" ~ 41, #ALABAMA	
      residence_state == "M1" ~ 41, #ALABAMA	
      residence_state == "02" ~ 81,#Alaska
      residence_state == "R0" ~ 81, #Alaska	
      residence_state == "N9" ~ 81, #Alaska
      residence_state == "98" ~ 61, #ARIZONA
      residence_state == "I8" ~ 61, #ARIZONA
      residence_state == "R8" ~ 61, #ARIZONA
      residence_state == "87" ~ 42, #ARKANSAS
      residence_state == "H7" ~ 42, #ARKANSAS
      residence_state == "Q7" ~ 42, #ARKANSAS
            residence_state == "91" ~ 71, #CALIFORNIA
      residence_state == "I1" ~ 71, #CALIFORNIA
      residence_state == "R1" ~ 71, #CALIFORNIA
      residence_state == "70" ~ 62, #COLORADO
      residence_state == "G0" ~ 62, #COLORADO
      residence_state == "P0" ~ 62, #COLORADO
            residence_state == "11" ~ 01, #CONNECTICUT
      residence_state == "A1" ~ 01, #CONNECTICUT
      residence_state == "J1" ~ 01, #CONNECTICUT
      residence_state == "21" ~ 11, #DELAWARE
      residence_state == "B1" ~ 11, #DELAWARE
      residence_state == "K1" ~ 11, #DELAWARE
            residence_state == "34" ~ 98, #DISTRICT OF COLUMBIA	
      residence_state == "C4" ~ 98, #DISTRICT OF COLUMBIA	
      residence_state == "L4" ~ 98, #DISTRICT OF COLUMBIA	
      residence_state == "42" ~ 43, #FLORIDA
      residence_state == "D2" ~ 43, #FLORIDA
      residence_state == "M2" ~ 43, #FLORIDA
            residence_state == "43" ~ 44, #GEORGIA
      residence_state == "D3" ~ 44, #GEORGIA
      residence_state == "R8" ~ 44, #GEORGIA
      residence_state == "03" ~ 82, #HAWAII
      residence_state == "92" ~ 63, #IDAHO
      residence_state == "I2" ~ 63, #IDAHO
            residence_state == "R2" ~ 63, #IDAHO
      residence_state == "61" ~ 21, #ILLINOIS
      residence_state == "F1" ~ 21, #ILLINOIS
      residence_state == "O1" ~ 21, #ILLINOIS
      residence_state == "51" ~ 22, #INDIANA	
      residence_state == "E1" ~ 22, #INDIANA	
            residence_state == "N1" ~ 22, #INDIANA	
      residence_state == "72" ~ 31, #IOWA
      residence_state == "G2" ~ 31, #IOWA
      residence_state == "P2" ~ 31, #IOWA
      residence_state == "73" ~ 32, #KANSAS
      residence_state == "G3" ~ 32, #KANSAS
            residence_state == "P3" ~ 32, #KANSAS
      residence_state == "52" ~ 51, #KENTUCKY
      residence_state == "E2" ~ 51, #KENTUCKY
      residence_state == "N2" ~ 51, #KENTUCKY
      residence_state == "88" ~ 45, #LOUISIANA
      residence_state == "H8" ~ 45, #LOUISIANA
            residence_state == "Q8" ~ 45, #LOUISIANA
      residence_state == "12" ~ 02, #MAINE
      residence_state == "A2" ~ 02, #MAINE
      residence_state == "J2" ~ 02, #MAINE
      residence_state == "31" ~ 52, #MARYLAND
      residence_state == "C1" ~ 52, #MARYLAND
            residence_state == "L1" ~ 52, #MARYLAND
      residence_state == "13" ~ 03, #MASSACHUSETTS
      residence_state == "A3" ~ 03, #MASSACHUSETTS
      residence_state == "J3" ~ 03, #MASSACHUSETTS
      residence_state == "62" ~ 23, #MICHIGAN
      residence_state == "F2" ~ 23, #MICHIGAN
            residence_state == "O2" ~ 23, #MICHIGAN
      residence_state == "74" ~ 33, #MINNESOTA
      residence_state == "G4" ~ 33, #MINNESOTA
      residence_state == "P4" ~ 33, #MINNESOTA
      residence_state == "45" ~ 46, #MISSISSIPPI
            residence_state == "D5" ~ 46, #MISSISSIPPI
      residence_state == "M5" ~ 46, #MISSISSIPPI
      residence_state == "75" ~ 34, #MISSOURI
      residence_state == "G5" ~ 34, #MISSOURI
      residence_state == "P5" ~ 34, #MISSOURI
      residence_state == "93" ~ 64, #MONTANA
            residence_state == "I3" ~ 64, #MONTANA
      residence_state == "38" ~ 64, #MONTANA
      residence_state == "76" ~ 35, #NEBRASKA
      residence_state == "G6" ~ 35, #NEBRASKA
      residence_state == "P6" ~ 35, #NEBRASKA
            residence_state == "94" ~ 65, #NEVADA
      residence_state == "I4" ~ 65, #NEVADA
      residence_state == "R4" ~ 65, #NEVADA
      residence_state == "14" ~ 04, #NEW HAMPSHIRE	
      residence_state == "A4" ~ 04, #NEW HAMPSHIRE	
      residence_state == "J4" ~ 04, #NEW HAMPSHIRE	
            residence_state == "22" ~ 12, #JERSEY
      residence_state == "B2" ~ 12, #JERSEY
      residence_state == "K2" ~ 12, #JERSEY
      residence_state == "83" ~ 66, #NEW MEXICO	
      residence_state == "H3" ~ 66, #NEW MEXICO	
            residence_state == "Q3" ~ 66, #NEW MEXICO	
      residence_state == "23" ~ 13,  #NEW YORK	
      residence_state == "B3" ~ 13, #NEW YORK	
      residence_state == "K3" ~ 13, #NEW YORK	
      residence_state == "46" ~ 47, #NORTH CAROLINA	
      residence_state == "D6" ~ 47, #NORTH CAROLINA	
            residence_state == "M6" ~ 47, #NORTH CAROLINA	
      residence_state == "77" ~ 36, #NORTH DAKOTA	
      residence_state == "G7" ~ 36, #NORTH DAKOTA	
      residence_state == "P7" ~ 36, #NORTH DAKOTA	
      residence_state == "53" ~ 24, #OHIO
            residence_state == "E3" ~ 24, #OHIO
      residence_state == "N3" ~ 24, #OHIO
      residence_state == "84" ~ 53, #OKLAHOMA
      residence_state == "H4" ~ 53, #OKLAHOMA
      residence_state == "Q4" ~ 53, #OKLAHOMA
      residence_state == "95" ~ 72, #OREGON
            residence_state == "I5" ~ 72, #OREGON
      residence_state == "R5" ~ 72, #OREGON
      residence_state == "32" ~ 14, #PENNSYLVANIA
      residence_state == "C2" ~ 14, #PENNSYLVANIA
      residence_state == "L2" ~ 14, #PENNSYLVANIA
            residence_state == "08" ~ 83, #PUERTO RICO
      residence_state == "15" ~ 05, #RHODE ISLAND	
      residence_state == "A5" ~ 05, #RHODE ISLAND	
      residence_state == "J5" ~ 05, #RHODE ISLAND	
      residence_state == "47" ~ 48, #SOUTH CAROLINA	
      residence_state == "D7" ~ 48, #SOUTH CAROLINA	
            residence_state == "M7" ~ 48, #SOUTH CAROLINA	
      residence_state == "78" ~ 37, #SOUTH DAKOTA	
      residence_state == "G8" ~ 37, #SOUTH DAKOTA	
      residence_state == "P8" ~ 37, #SOUTH DAKOTA	
      residence_state == "48" ~ 54, #TENNESSEE	
            residence_state == "D8" ~ 54, #TENNESSEE	
      residence_state == "M8" ~ 54, #TENNESSEE	
      residence_state == "85" ~ 49, #TEXAS
      residence_state == "H5" ~ 49, #TEXAS
      residence_state == "Q5" ~ 49, #TEXAS
      residence_state == "96" ~ 67, #UTAH
            residence_state == "I6" ~ 67, #UTAH
      residence_state == "R6" ~ 67, #UTAH
      residence_state == "16" ~ 06, #VERMONT
      residence_state == "A6" ~ 06, #VERMONT
      residence_state == "J6" ~ 06, #VERMONT
            residence_state == "33" ~ 4, #VIRGINIA
      residence_state == "C3" ~ 40, #VIRGINIA
      residence_state == "L3" ~ 40, #VIRGINIA
      residence_state == "97" ~ 40, #WASHINGTON
      residence_state == "I7" ~ 73, #WASHINGTON
      residence_state == "R7" ~ 73, #WASHINGTON
            residence_state == "54" ~ 56, #WEST VIRGINIA	
      residence_state == "E4" ~ 56, #WEST VIRGINIA	
      residence_state == "N4" ~ 56, #WEST VIRGINIA	
      residence_state == "63" ~ 25, #WISCONSIN
      residence_state == "F3" ~ 25, #WISCONSIN
            residence_state == "O3" ~ 25, #WISCONSIN
      residence_state == "79" ~ 8, #WYOMING
      residence_state == "G9" ~ 9,#WYOMING 
      residence_state == "P9" ~ 3, #WYOMING
      residence_state == "&" ~ 12, #WYOMING
      TRUE ~ NA_real_     
      ))
  
  ## return data.frame   
  return(df)
}

```

```{r}
res_state_recode <- recode_res_state_enlistment(df = data_combined) %>% 
  select(residence_state, state_recode)
```

#Load csv with NARA AAD codes
```{r}
civ_occupation_codes <- read_csv(civ_path)
```

#view civ_occupation fields
```{r}
data_combined %>% 
  count(civ_occupation) 
```
## write a function to recode civ_occupation codes to better match NARA AAD codes 

```{r}
recode_civ_occupation_enlistment <- function(df){
  
  ## recode civ_occupation variable
  df <- df %>% 
    mutate(civ_occupation_recode = case_when(
      civ_occupation == 001 ~ 001, #Accountants and auditors
      civ_occupation == 002 ~ 002, #Actors and actresses	
      civ_occupation == 081 ~ 081, #Advertising agents	
      civ_occupation == 148 ~ 148, #Agents and appraisers, n.e.c.	
      civ_occupation == 349 ~ 349, #Agricultural occupations, n.e.c.	
      civ_occupation == 307 ~ 307, #Animal and livestock farmers	
      civ_occupation == 797 ~ 797, #Apprentices to other construction and hand trades
      civ_occupation == 799 ~ 799, #Apprentices to other trades	
      civ_occupation == 798 ~ 798, #Apprentices to printing trades	
      civ_occupation == 247 ~ 247, #Apprentices to service occupations	
      civ_occupation == 003 ~ 003, #Architects	
      civ_occupation == 004 ~ 004, #Artists, sculptors, and teachers of art	
      civ_occupation == 057 ~ 057, #Athletes, sports instructors, and sports #officials	
      civ_occupation == 760 ~ 760, #Attendants, filling stations and parking lots	
      civ_occupation == 242 ~ 242, #Attendants, hospitals and other institutions, #n.e.c.	
      civ_occupation == 243 ~ 243, #Attendants, professional and personal service, #n.e.c.	
      civ_occupation == 240 ~ 240, #Attendants, recreation and amusement, n.e.c.	
      civ_occupation == 151 ~ 151, #Auctioneers	
      civ_occupation == 006 ~ 006, #Authors, editors, and reporters	
      civ_occupation == 041 ~ 041, #Aviators
      civ_occupation == 292 ~ 292, #Baggage porters	
      civ_occupation == 143 ~ 143, #Baggagemen, transportation	
      civ_occupation == 401 ~ 401, #Bakers	
      civ_occupation == 232 ~ 232, #Barbers, beauticians, and manicurists	
      civ_occupation == 344 ~ 344, #Barn bosses	
      civ_occupation == 221 ~ 221, #Bartenders	
      civ_occupation == 222 ~ 222, #Bellmen and related occupations	
      civ_occupation == 331 ~ 331, #Blight control laborers and bindweed eradicators	
      civ_occupation == 223 ~ 223, #Boarding-house and lodging-house keepers	
      civ_occupation == 234 ~ 234, #Bookblacks	
      civ_occupation == 101 ~ 101, #Bookkeepers and cashiers, except bank cashiers	
      civ_occupation == 102 ~ 102, #Bookkeeping machine operators	
      civ_occupation == 074 ~ 074, #Buyers and department heads, stores	
      civ_occupation == 432 ~ 432, #Cabinetmakers
      civ_occupation == 244 ~ 244, #Camp attendants	
      civ_occupation == 155 ~ 155, #Canvassers and solicitors	
      civ_occupation == 525 ~ 525, #Carpenters	
      civ_occupation == 793 ~ 793, #Carpenters apprentices
      civ_occupation == 301 ~ 301, #Cash grain farmers	
      civ_occupation == 282 ~ 282, #Charwomen and cleaners
      civ_occupation == 103 ~ 103, #Checkers	
      civ_occupation == 007 ~ 007, #Chemists, assayers, and metallurgists	
      civ_occupation == 042 ~ 042, #Chiropractors	
      civ_occupation == 008 ~ 008, #Clergymen
      civ_occupation == 149 ~ 149, #Clerks and kindred occupations, n.e.c.	
      civ_occupation == 112 ~ 112, #Clerks in trade, n.e.c	
      civ_occupation == 104 ~ 104, #Clerks, general	
      civ_occupation == 105 ~ 105, #Clerks, general office	
      civ_occupation == 115 ~ 115, #Collectors, bills and accounts	
      civ_occupation == 011 ~ 011, #College presidents, professors, and instructors	
      civ_occupation == 044 ~ 044, #College presidents, professors, and instructors	
      civ_occupation == 539 ~ 539, #Conductors, bus and street railway	
      civ_occupation == 092 ~ 092, #Conductors, railroad	
      civ_occupation == 205 ~ 205, #Cooks, domestic	
      civ_occupation == 226 ~ 226, #Cooks, except private family	  
      civ_occupation == 116 ~ 116, #Correspondence clerks	
      civ_occupation == 302 ~ 302, #Cotton farmers	
      civ_occupation == 347 ~ 347, #Cotton ginners	
      civ_occupation == 012 ~ 012, #County agents and farm demonstrators	
      civ_occupation == 085 ~ 085, #Credit men	
      civ_occupation == 303 ~ 303, #Crop specialty farmers	
      civ_occupation == 262 ~ 262, #Crossing watchmen and bridge tenders	
      civ_occupation == 304 ~ 304, #Dairy farmers	
      civ_occupation == 045 ~ 045, #Dancers and chorus girls	
      civ_occupation == 201 ~ 201, #Day workers	
      civ_occupation == 043 ~ 043, #Decorators and window dressers	
      civ_occupation == 156 ~ 156, #Demonstrators
      civ_occupation == 013 ~ 013, #Dentists
      civ_occupation == 046 ~ 046, #Designers
      civ_occupation == 245 ~ 245, #Doormen
      civ_occupation == 048 ~ 048, #Draftsmen
      civ_occupation == 497 ~ 497, #Electricians	
      civ_occupation == 795 ~ 795, #Electricians apprentices	
      civ_occupation == 445 ~ 445, #Electrotypers and stereotypers	
      civ_occupation == 295 ~ 295, #Elevator operators	
      civ_occupation == 065 ~ 065, #Embalmers and undertakers	
      civ_occupation == 015 ~ 015, #Engineers, chemical
      civ_occupation == 016 ~ 016, #Engineers, civil	
      civ_occupation == 018 ~ 018, #Engineers, industrial	
      civ_occupation == 019 ~ 019, #Engineers, mechanical	
      civ_occupation == 020 ~ 020, #Engineers, mining	
      civ_occupation == 473 ~ 473, #Engravers	
      civ_occupation == 673 ~ 673, #Engravers	 
      civ_occupation == 131 ~ 131, #Express messengers and railway mail clerks	
      civ_occupation == 489 ~ 489, #Extruder operator II (nonfer. metal alloys & prod.) Extrusion-press operator	
      civ_occupation == 336 ~ 336, #Farm couples	
      civ_occupation == 317 ~ 317, #Farm hands, animal and livestock	
      civ_occupation == 312 ~ 312, #Farm hands, cotton	
      civ_occupation == 313 ~ 313, #Farm hands, crop specialty	
      civ_occupation == 314 ~ 314, #Farm hands, dairy	
      civ_occupation == 315 ~ 315, #Farm hands, fruit	
      civ_occupation == 316 ~ 316, #Farm hands, general farms	
      civ_occupation == 311 ~ 311, #Farm hands, grain	
      civ_occupation == 318 ~ 318, #Farm hands, poultry	
      civ_occupation == 319 ~ 319, #Farm hands, vegetables	
      civ_occupation == 337 ~ 337, #Farm managers and foremen	
      civ_occupation == 335 ~ 335, #Farm mechanics	
      civ_occupation == 117 ~ 117, #File clerks	
      civ_occupation == 106 ~ 106, #Financial institution clerks, n.e.c.	
      civ_occupation == 263 ~ 263, #Firemen, fire department	
      civ_occupation == 770 ~ 770, #Firemen, other than process firemen	
      civ_occupation == 387 ~ 387, #Fishermen and oystermen	
      civ_occupation == 389 ~ 389, #Fishing occupations, n.e.c.	
      civ_occupation == 075 ~ 075, #Floormen and floor managers, stores	
      civ_occupation == 594 ~ 594, #Foremen, construction	
      civ_occupation == 593 ~ 593, #Foremen, extraction of minerals	
      civ_occupation == 592 ~ 592, #Foremen, manufacturing	
      civ_occupation == 591 ~ 591, #Foremen, manufacturing	
      civ_occupation == 599 ~ 599, #Foremen, n.e.c.	
      civ_occupation == 597 ~ 597, #Foremen, services amusements	
      civ_occupation == 595 ~ 595, #Foremen, tranportation, communications, and utilities	
      civ_occupation == 391 ~ 391, #Foremen, tranportation, communications, and utilities	
      civ_occupation == 482 ~ 482, #Foundry occupations, n.e.c.	
      civ_occupation == 330 ~ 330, #Fruit and vegetable graders and packers	
      civ_occupation == 305 ~ 305, #Fruit farmers	
      civ_occupation == 340 ~ 340, #Gardeners and grounds keepers, parks, cemetaries, etc.	
      civ_occupation == 745 ~ 745, #Gatemen and train callers	
      civ_occupation == 119 ~ 119, #General Industrial Clerks (Office), n.e.c.	
      civ_occupation == 306 ~ 306, #General farmers	
      civ_occupation == 118 ~ 118, #General industry clerks	
      civ_occupation == 577 ~ 577, #Glaziers	
      civ_occupation == 261 ~ 261, #Guards and watchmen, except crossing watchmen	
      civ_occupation == 236 ~ 236, #Guides, except hunting and trapping	
      civ_occupation == 341 ~ 341, #Hatchery men	
      civ_occupation == 052 ~ 052, #Healers and medical service occupations, n.e.c.	
      civ_occupation == 071 ~ 071, #Hotel and restaurant managers	
      civ_occupation == 107 ~ 107, #Hotel clerks, n.e.c.	
      civ_occupation == 203 ~ 203, #Housekeepers, private family	 
      civ_occupation == 225 ~ 225, #Housekeepers, stewards, and hostesses	
      civ_occupation == 204 ~ 204, #Housemen and yardmen	
      civ_occupation == 161 ~ 161, #Hucksters and peddlers	
      civ_occupation == 397 ~ 397, #Hunters and trappers	
      civ_occupation == 396 ~ 396, #Hunting and trapping guides	
      civ_occupation == 079 ~ 079, #Inspectors, managerial and official	
      civ_occupation == 095 ~ 095, #Inspectors, public service, n.e.c.	
      civ_occupation == 108 ~ 108, #Insurance clerks, n.e.c.	
      civ_occupation == 332 ~ 332, #Irrigation occupations	
      civ_occupation == 284 ~ 284, #Janitors and sextons	
      civ_occupation == 471 ~ 471, #Jewelers, watchmakers, goldsmiths, and silversmiths	
      civ_occupation == 229 ~ 229, #Kitchen workers in hotels, restaurants, railroads, steamships, etc., n.e.c.	
      civ_occupation == 050 ~ 050, #Laboratory technicians and assistants	
      civ_occupation == 342 ~ 342, #Laborers, hatchery	
      civ_occupation == 202 ~ 202, #Laundresses, private family	
      civ_occupation == 022 ~ 022, #Lawyers and judges	
      civ_occupation == 023 ~ 023, #Librarians	
      civ_occupation == 120 ~ 120, #Library assistants and attendants	
      civ_occupation == 446 ~ 446, #Lithographers	
      civ_occupation == 541 ~ 541, #Locomotive engineers	
      civ_occupation == 542 ~ 542, #Locomotive firemen	
      civ_occupation == 416 ~ 416, #Loom fixers	
      civ_occupation == 478 ~ 478, #Machine shop and related occupations, n.e.c.	
      civ_occupation == 475 ~ 475, #Machinists	
      civ_occupation == 794 ~ 794, #Machinists apprentices	
      civ_occupation == 224 ~ 224, #Maids and housemen, hotels, restaurants, etc.	
      civ_occupation == 206 ~ 206, #Maids, general	
      civ_occupation == 128 ~ 128, #Mail carriers	
      civ_occupation == 097 ~ 097, #Managers and officials, n.e.c.	
      civ_occupation == 099 ~ 099, #Managers and officials, n.e.c.	
      civ_occupation == 098 ~ 098, #Managers and officials, n.e.c.	
      civ_occupation == 087 ~ 087, #Managers and superintendents, buildings	
      civ_occupation == 580 ~ 580, #Mechanics and repairmen, airplane	
      civ_occupation == 780 ~ 780, #Mechanics and repairmen, airplane	
      civ_occupation == 123 ~ 123, #Messengers, errand boys, and office boys and girls	
      civ_occupation == 238 ~ 238, #Midwives and practical nurses	
      civ_occupation == 423 ~ 423, #Milliners	
      civ_occupation == 578 ~ 578, #Millwrights
      civ_occupation == 209 ~ 209, #Miscellaneous servants, private family	
      civ_occupation == 543 ~ 543, #Motormen, street, subway, and elevated railway	     
      civ_occupation == 024 ~ 024, #Motormen, street, subway, and elevated railway	
      civ_occupation == 158 ~ 158, #Newsboys	
      civ_occupation == 207 ~ 207, #Nursemaids	
      civ_occupation == 339 ~ 339, #Nursery and landscaping laborers	
      civ_occupation == 338 ~ 338, #Nursery operators and flower growers	
      civ_occupation == 404 ~ 404, #Occupations in furnishing utilities, n.e.c.	
      civ_occupation == 554 ~ 554, #Occupations in furnishing utilities, n.e.c.	
      civ_occupation == 502 ~ 502, #Occupations in manufacture of automobiles, n.e.c.	
      civ_occupation == 442 ~ 442, #Occupations in manufacture of paper goods	
      civ_occupation == 454 ~ 454, #Occupations in production of ammunition	
      civ_occupation == 654 ~ 654, #Occupations in production of ammunition	
      civ_occupation == 854 ~ 854, #Occupations in production of ammunition	
      civ_occupation == 908 ~ 908, #Occupations in production of ammunition	
      civ_occupation == 467 ~ 467, #Occupations in production of cement, concrete, gypsum, and plaster products	
      civ_occupation == 456 ~ 456, #Occupations in production of miscellaneous petroleum and coal products	
      civ_occupation == 520 ~ 520, #Occupations in production of petroleum	
      civ_occupation == 125 ~ 125, #Office machine operators	
      civ_occupation == 083 ~ 083, #Officials of lodges, societies, unions, etc.	  
      civ_occupation == 708 ~ 708, #Opticians and lens grinders and polishers	
      civ_occupation == 508 ~ 508, #Opticians, lens grinders, and polishers	
      civ_occupation == 053 ~ 053, #Optometrists	
      civ_occupation == 768 ~ 768, #Packing, filling, labeling, marking, bottling, and related occupations, n.e.c.	
      civ_occupation == 528 ~ 528, #Paperhangers	
      civ_occupation == 208 ~ 208, #Parlormaids	
      civ_occupation == 126 ~ 126, #Paymasters, payroll clerks, and timekeepers	
      civ_occupation == 025 ~ 025, #Pharmacists	
      civ_occupation == 056 ~ 056, #Photgraphers	
      civ_occupation == 447 ~ 447, #Photoengravers	
      civ_occupation == 132 ~ 132, #Physicians and dentists assistants and attendants	
      civ_occupation == 026 ~ 026, #Physicians and surgeons	
      civ_occupation == 512 ~ 512, #Piano and organ tuners	
      civ_occupation == 529 ~ 529, #Plasterers	
      civ_occupation == 796 ~ 796, #Plumbers apprentices	
      civ_occupation == 530 ~ 530, #Plumbers, gas fitters, and steam fitters	
      civ_occupation == 265 ~ 265, #Policemen and detectives, except in public service	
      civ_occupation == 266 ~ 266, #Policemen and detectives, public service	
      civ_occupation == 286 ~ 286, #Porters, n.e.c.	
      civ_occupation == 127 ~ 127, #Post office clerks	
      civ_occupation == 308 ~ 308, #Poultry farmers	
      civ_occupation == 551 ~ 551, #Power station operators	
      civ_occupation == 448 ~ 448, #Pressmen and plate printers, printing	
      civ_occupation == 110 ~ 110, #Printing and publishing clerks, n.e.c	
      civ_occupation == 038 ~ 038, #Professional occupations, n.e.c.	
      civ_occupation == 039 ~ 039, #Professional occupations, n.e.c.	
      civ_occupation == 094 ~ 094, #Public officials, n.e.c.	
      civ_occupation == 291 ~ 291, #Pullman porters	
      civ_occupation == 091 ~ 091, #Purchasing agents and buyers, n.e.c.	  
      civ_occupation == 061 ~ 061, #Radio operators	
      civ_occupation == 111 ~ 111, #Railroad clerks, n.e.c.	
      civ_occupation == 072 ~ 072, #Retail managers	
      civ_occupation == 731 ~ 731, #Roofers and slaters	
      civ_occupation == 548 ~ 548, #Sailors and deck hands, except U.S. Navy	
      civ_occupation == 180 ~ 180, #Salemen, to consumers	
      civ_occupation == 196 ~ 196, #Sales clerk, dry cleaning and laundry	
      civ_occupation == 170 ~ 170, #Sales clerks	
      civ_occupation == 187 ~ 187, #Salesmen and sales agents, except to consumers	
      civ_occupation == 185 ~ 185, #Salesmen and sales agents, except to consumers	
      civ_occupation == 186 ~ 186, #Salesmen and sales agents, except to consumers	
      civ_occupation == 152 ~ 152, #Salesmen, brokerage and commission firms, n.e.c.	
      civ_occupation == 157 ~ 157, #Salesmen, insurance	
      civ_occupation == 163 ~ 163, #Salesmen, real estate	
      civ_occupation == 165 ~ 165, #Salesmen, stock and bond	
      civ_occupation == 175 ~ 175, #Salespersons	
      civ_occupation == 133 ~ 133, #Secretaries	
      civ_occupation == 069 ~ 069, #Semiprofessional occupations, n.e.c.	
      civ_occupation == 068 ~ 068, #Semiprofessional occupations, n.e.c.	
      civ_occupation == 621 ~ 621, #Semiskilled Furriers and occupations in fabrication of fur good, n.e.c.	 
      civ_occupation == 629 ~ 629, #Semiskilled Inspectors, scalers, and graders, logs and lumber	
      civ_occupation == 635 ~ 635, #Semiskilled Upholsterers	
      civ_occupation == 756 ~ 756, #Semiskilled amusement, recreation, and motion picture occupations, n.e.c.	
      civ_occupation == 733 ~ 733, #Semiskilled asbestos and insulation workers	
      civ_occupation == 686 ~ 686, #Semiskilled blacksmiths, forgemen, and hammermen	
      civ_occupation == 774 ~ 774, #Semiskilled blasters and powdermen	
      civ_occupation == 683 ~ 683, #Semiskilled boilermakers	
      civ_occupation == 738 ~ 738, #Semiskilled brakemen, railroad	
      civ_occupation == 724 ~ 724, #Semiskilled brick and stone masons, and tile setters	     
      civ_occupation == 726 ~ 726, #Semiskilled cement and concrete finishers	
      civ_occupation == 787 ~ 787, #Semiskilled chainmen, rodmen, and axmen, surveying	
      civ_occupation == 736 ~ 736, #Semiskilled chauffeurs and drivers, bus, taxi, truck, and tractor	
      civ_occupation == 644 ~ 644, #Semiskilled compositors and typesetters	
      civ_occupation == 723 ~ 723, #Semiskilled construction machinery operators, n.e.c.	
      civ_occupation == 732 ~ 732, #Semiskilled construction occupations, n.e.c.	
      civ_occupation == 638 ~ 638, #Semiskilled cooperage occupations, n.e.c.	
      civ_occupation == 773 ~ 773, #Semiskilled cranemen, derrickmen, hoistmen, and shovelmen	
      civ_occupation == 625 ~ 625, #Semiskilled dressmakers and seamstresses	
      civ_occupation == 775 ~ 775, #Semiskilled drillers, extraction of minerals and construction	
      civ_occupation == 718 ~ 718, #Semiskilled dyers	    
      civ_occupation == 772 ~ 772, #Semiskilled engineers, stationary	
      civ_occupation == 677 ~ 677, #Semiskilled filers, grinders, buffers, and polishers (metal)	
      civ_occupation == 682 ~ 682, #Semiskilled foundry occupations, n.e.c.	
      civ_occupation == 691 ~ 691, #Semiskilled furnacemen, smelters, and pourers	
      civ_occupation == 785 ~ 785, #Semiskilled garage laborers and car washers and greasers	
      civ_occupation == 633 ~ 633, #Semiskilled general woodworking occupations, n.e.c.	
      civ_occupation == 777 ~ 777, #Semiskilled glaziers	
      civ_occupation == 687 ~ 687, #Semiskilled heat treaters, annealers, and temperers	
      civ_occupation == 776 ~ 776, #Semiskilled inspectors, n.e.c.	  
      civ_occupation == 695 ~ 695, #Semiskilled inter-industry metal working occupations, n.e.c.	
      civ_occupation == 753 ~ 753, #Semiskilled linemen and servicemen, telegraph, telephone, and power
      civ_occupation == 747 ~ 747, #Semiskilled longshoremen and stevedores	
      civ_occupation == 630 ~ 630, #Semiskilled lumbermen, raftsmen, and woodchoppers	
      civ_occupation == 678 ~ 678, #Semiskilled machine shop and related occupations, n.e.c.	
      civ_occupation == 758 ~ 758, #Semiskilled meatcutters, except in slaughtering and packing houses
      civ_occupation == 781 ~ 781, #Semiskilled mechanics and repairmen, motor vehicles	
      civ_occupation == 783 ~ 783, #Semiskilled mechanics and repairmen, n.e.c.	
      civ_occupation == 779 ~ 779, #Semiskilled mechanics and repairmen, railroad and carshop	
      civ_occupation == 607 ~ 607, #Semiskilled millers, grain, glour, feed, etc.	
      civ_occupation == 721 ~ 721, #Semiskilled miners, and mining-machine operators	
      civ_occupation == 789 ~ 789, #Semiskilled miscellaneous occupations, n.e.c.	
      civ_occupation == 755 ~ 755, #Semiskilled motion picture projectionists	
      civ_occupation == 740 ~ 740, #Semiskilled motormen (vehicle), except railroad, railway, and bus	
      civ_occupation == 763 ~ 763, #Semiskilled nonprocess occupations in manufacturing, n.e.c.	
      civ_occupation == 765 ~ 765, #Semiskilled nonprocess occupations in manufacturing, n.e.c.	
      civ_occupation == 764 ~ 764, #Semiskilled nonprocess occupations in manufacturing, n.e.c.	
      civ_occupation == 618 ~ 618, #Semiskilled nonprocess occupations, in manufacture of textiles, n.e.c.	
      civ_occupation == 703 ~ 703, #Semiskilled occupations in building of aircraft, n.e.c.	
      civ_occupation == 705 ~ 705, #Semiskilled occupations in building transportation equipment (except automobiles and aircraft), n.e.c.	  
      civ_occupation == 604 ~ 604, #Semiskilled occupations in canning and preserving of foods	
      civ_occupation == 674 ~ 674, #Semiskilled occupations in electroplating, galvanizing, and related processes	
      civ_occupation == 722 ~ 722, #Semiskilled occupations in extraction of minerals, n.e.c.	
      civ_occupation == 693 ~ 693, #Semiskilled occupations in fabrication of metal products, n.e.c.	
      civ_occupation == 694 ~ 694, #Semiskilled occupations in fabrication of metal products, n.e.c.	
      civ_occupation == 627 ~ 627, #Semiskilled occupations in fabrication of metal products, n.e.c.	
      civ_occupation == 754 ~ 754, #Semiskilled occupations in furnishing utilities, n.e.c.	
      civ_occupation == 757 ~ 757, #Semiskilled occupations in laundering, cleaning, dyeing, and pressing apparel and other articles	
      civ_occupation == 702 ~ 702, #Semiskilled occupations in manufacture of automobiles, n.e.c.	 
      civ_occupation == 661 ~ 661, #Semiskilled occupations in manufacture of boots and shoes	
      civ_occupation == 672 ~ 672, #Semiskilled occupations in manufacture of clocks, watches, jewelry, and articles of precious metals	
      civ_occupation == 699 ~ 699, #Semiskilled occupations in manufacture of electrical machinery and accessories, n.e.c.	
      civ_occupation == 710 ~ 710, #Semiskilled occupations in manufacture of fabricated plastic products	
      civ_occupation == 636 ~ 636, #Semiskilled occupations in manufacture of furniture, n.e.c.	
      civ_occupation == 624 ~ 624, #Semiskilled occupations in manufacture of hats and caps, n.e.c.	
      civ_occupation == 614 ~ 614, #Semiskilled occupations in manufacture of knit goods	
      civ_occupation == 659 ~ 659, #Semiskilled occupations in manufacture of leather	
      civ_occupation == 662 ~ 662, #Semiskilled occupations in manufacture of leather products other than boots and shoes	
      civ_occupation == 700 ~ 700, #Semiskilled occupations in manufacture of miscellaneous electrical equipment, n.e.c.	
      civ_occupation == 639 ~ 639, #Semiskilled occupations in manufacture of miscellaneous finished lumber products, n.e.c.	
      civ_occupation == 641 ~ 641, #Semiskilled occupations in manufacture of paper and pulp	
      civ_occupation == 642 ~ 642, #Semiskilled occupations in manufacture of paper goods	
      civ_occupation == 709 ~ 709, #Semiskilled occupations in manufacture of professional and scientific apparatus, n.e.c.	
      civ_occupation == 698 ~ 698, #Semiskilled occupations in manufacture of radios and phonographs	
      civ_occupation == 619 ~ 619, #Semiskilled occupations in manufacture of textiles, n.e.c.	
      civ_occupation == 612 ~ 612, #Semiskilled occupations in manufacture of tobacco products	
      civ_occupation == 688 ~ 688, #Semiskilled occupations in mechanical treatment of metals (rolling, stamping, forging, pressing, etc.), n.e.c.	
      civ_occupation == 649 ~ 649, #Semiskilled occupations in printing and publishing, n.e.c.	
      civ_occupation == 606 ~ 606, #Semiskilled occupations in processing of dairy products	     
      civ_occupation == 670 ~ 670, #Semiskilled occupations in production of asbestos products, abrasives, and polishing products	
      civ_occupation == 602 ~ 602, #Semiskilled occupations in production of bakery products, n.e.c.	
      civ_occupation == 603 ~ 603, #Semiskilled occupations in production of beverages	
      civ_occupation == 667 ~ 667, #Semiskilled occupations in production of cement, concrete, gypsum, and plaster product	
      civ_occupation == 653 ~ 653, #Semiskilled occupations in production of chemical products, n.e.c.	
      civ_occupation == 666 ~ 666, #Semiskilled occupations in production of clay products	
      civ_occupation == 605 ~ 605, #Semiskilled occupations in production of confections	
      civ_occupation == 692 ~ 692, #Semiskilled occupations in production of ferrous and nonferrous metals, n.e.c.	
      civ_occupation == 665 ~ 665, #Semiskilled occupations in production of glass and glass products	
      civ_occupation == 608 ~ 608, #Semiskilled occupations in production of grain-mill products, n.e.c.	
      civ_occupation == 652 ~ 652, #Semiskilled occupations in production of industrial chemicals	
      civ_occupation == 610 ~ 610, #Semiskilled occupations in production of miscellaneous food products	
      civ_occupation == 656 ~ 656, #Semiskilled occupations in production of miscellaneous petroleum and coal products	
      civ_occupation == 650 ~ 650, #Semiskilled occupations in production of paint and varnish	
      civ_occupation == 720 ~ 720, #Semiskilled occupations in production of petroleum	
      civ_occupation == 657 ~ 657, #Semiskilled occupations in production of rubber goods	
      civ_occupation == 651 ~ 651, #Semiskilled occupations in production of synthetic fibers and processing of chemicals and other materials, n.e.c.	
      civ_occupation == 655 ~ 655, #Semiskilled occupations in refining of petroleum	   
      civ_occupation == 609 ~ 609, #Semiskilled occupations in slaughtering and in preparation of meat products	
      civ_occupation == 669 ~ 669, #Semiskilled occupations in stoneworking, n.e.c.	
      civ_occupation == 713 ~ 713, #Semiskilled occupations in the manufacture of miscellaneous products	
      civ_occupation == 759 ~ 759, #Semiskilled occupations in trades and services, n.e.c.	
      civ_occupation == 771 ~ 771, #Semiskilled oilers of machinery	
      civ_occupation == 690 ~ 690, #Semiskilled ore dressing occupations	
      civ_occupation == 727 ~ 727, #Semiskilled painters, construction and maintenance	
      civ_occupation == 716 ~ 716, #Semiskilled painters, except construction and maintenance	
      civ_occupation == 717 ~ 717, #Semiskilled pattern and model makers, except paper	
      civ_occupation == 786 ~ 786, #Semiskilled photographic process occupations	
      civ_occupation == 634 ~ 634, #Semiskilled planing mill occupations, n.e.c.	 
      civ_occupation == 761 ~ 761, #Semiskilled public service occupations, n.e.c.	
      civ_occupation == 735 ~ 735, #Semiskilled routemen	
      civ_occupation == 748 ~ 748, #Semiskilled sailors and deckhands, except U.S. Navy	
      civ_occupation == 631 ~ 631, #Semiskilled sawmill occupations, n.e.c.	
      civ_occupation == 684 ~ 684, #Semiskilled structural- and ornamental-metal workers	
      civ_occupation == 744 ~ 744, #Semiskilled switchmen, railroad	
      civ_occupation == 734 ~ 734, #Semiskilled teamsters	
      civ_occupation == 784 ~ 784, #Semiskilled tool sharpeners and dressers	
      civ_occupation == 749 ~ 749, #Semiskilled transportation occupations, n.e.c.	   
      civ_occupation == 788 ~ 788, #Semiskilled warehousing, storekeeping, handling, loading, unloading, and related occupations, n.e.c.	
      civ_occupation == 685 ~ 685, #Semiskilled welders and flame cutters	
      civ_occupation == 267 ~ 267, #Sheriffs and bailiffs	
      civ_occupation == 088 ~ 088, #Ship captains, mates, pilots, and engineers	
      civ_occupation == 228 ~ 228, #Ship stewards	
      civ_occupation == 134 ~ 134, #Shipping and receiving clerks	
      civ_occupation == 660 ~ 660, #Shoemakers and shoe repairmen, not in factory	
      civ_occupation == 460 ~ 460, #Shoemakers and shoe repairmen, not in factory	
      civ_occupation == 197 ~ 197, #Shoppers	 
      civ_occupation == 062 ~ 062, #Showmen
      civ_occupation == 421 ~ 421, #Skilled Furriers and occupations in fabrication of fur good, n.e.c.
      civ_occupation == 429 ~ 429, #Skilled Inspectors, scalers, and graders, logs and lumber	
      civ_occupation == 521 ~ 521, #Skilled Miners, and mining-machine operators	
      civ_occupation == 435 ~ 435, #Skilled Upholsterers	
      civ_occupation == 556 ~ 556, #Skilled amusement, recreation, and motion picture occupations, n.e.c.	
      civ_occupation == 533 ~ 533, #Skilled asbestos and insulation workers	
      civ_occupation == 486 ~ 486, #Skilled blacksmiths, forgemen, and hammermen	
      civ_occupation == 574 ~ 574, #Skilled blasters and powdermen	
      civ_occupation == 483 ~ 483, #Skilled boilermakers	
      civ_occupation == 538 ~ 538, #Skilled brakemen, railroad	
      civ_occupation == 524 ~ 524, #Skilled brick and stone masons, and tile setters	
      civ_occupation == 526 ~ 526, #Skilled cement and concrete finishers	
      civ_occupation == 536 ~ 536, #Skilled chauffeurs and drivers, bus, taxi, truck, and tractor	
      civ_occupation == 444 ~ 444, #Skilled compositors and typesetters	
      civ_occupation == 523 ~ 523, #Skilled construction machinery operators, n.e.c.	
      civ_occupation == 532 ~ 532, #Skilled construction occupations, n.e.c.	
      civ_occupation == 438 ~ 438, #Skilled cooperage occupations, n.e.c.	
      civ_occupation == 573 ~ 573, #Skilled cranemen, derrickmen, hoistmen, and shovelmen	
      civ_occupation == 425 ~ 425, #Skilled dressmakers and seamstresses	   
      civ_occupation == 575 ~ 575, #Skilled drillers, extraction of minerals and construction	
      civ_occupation == 518 ~ 518, #Skilled dyers	
      civ_occupation == 572 ~ 572, #Skilled engineers, stationary	
      civ_occupation == 477 ~ 477, #Skilled filers, grinders, buffers, and polishers (metal)	
      civ_occupation == 491 ~ 491, #Skilled furnacemen, smelters, and pourers	
      civ_occupation == 433 ~ 433, #Skilled general woodworking occupations, n.e.c.	
      civ_occupation == 487 ~ 487, #Skilled heat treaters, annealers, and temperers	
      civ_occupation == 576 ~ 576, #Skilled inspectors, n.e.c.	
      civ_occupation == 495 ~ 495, #Skilled inter-industry metal working occupations, n.e.c.	  
      civ_occupation == 553 ~ 553, #Skilled linemen and servicemen, telegraph, telephone, and power	
      civ_occupation == 430 ~ 430, #Skilled lumbermen, raftsmen, and woodchoppers	
      civ_occupation == 558 ~ 558, #Skilled meatcutters, except in slaughtering and packing houses	
      civ_occupation == 581 ~ 581, #Skilled mechanics and repairmen, motor vehicles	
      civ_occupation == 583 ~ 583, #Skilled mechanics and repairmen, n.e.c.	
      civ_occupation == 579 ~ 579, #Skilled mechanics and repairmen, railroad and carshop	
      civ_occupation == 407 ~ 407, #Skilled millers, grain, flour, feed, etc.	
      civ_occupation == 589 ~ 589, #Skilled miscellaneous occupations, n.e.c.	
      civ_occupation == 481 ~ 481, #Skilled molders	
      civ_occupation == 555 ~ 555, #Skilled motion picture projectionists	
      civ_occupation == 540 ~ 540, #Skilled motormen (vehicle), except railroad, railway, and bus	   
      civ_occupation == 418 ~ 418, #Skilled nonprocess occupations, in manufacture of textiles, n.e.c.
      civ_occupation == 503 ~ 503, #Skilled occupations in building of aircraft, n.e.c.	
      civ_occupation == 505 ~ 505, #Skilled occupations in building transportation equipment (except automobiles and aircraft), n.e.c.	
      civ_occupation == 474 ~ 474, #Skilled occupations in electroplating, galvanizing, and related processes	
      civ_occupation == 493 ~ 493, #Skilled occupations in fabrication of metal products, n.e.c.	
      civ_occupation == 494 ~ 494, #Skilled occupations in fabrication of metal products, n.e.c.	
      civ_occupation == 427 ~ 427, #Skilled occupations in fabrication of textile products, n.e.c.	
      civ_occupation == 557 ~ 557, #Skilled occupations in laundering, cleaning, dyeing, and pressing apparel and other articles	
      civ_occupation == 461 ~ 461, #Skilled occupations in manufacture of boots and shoes	
      civ_occupation == 472 ~ 472, #Skilled occupations in manufacture of clocks, watches, jewelry, and articles of precious metals	
      civ_occupation == 499 ~ 499, #Skilled occupations in manufacture of electrical machinery and accessories, n.e.c.	
      civ_occupation == 510 ~ 510, #Skilled occupations in manufacture of fabricated plastic products	
      civ_occupation == 436 ~ 426, #Skilled occupations in manufacture of furniture, n.e.c.	
      civ_occupation == 424 ~ 424, #Skilled occupations in manufacture of hats and caps, n.e.c.	
      civ_occupation == 414 ~ 414, #Skilled occupations in manufacture of knit goods	
      civ_occupation == 459 ~ 459, #Skilled occupations in manufacture of leather	
      civ_occupation == 462 ~ 462, #Skilled occupations in manufacture of leather products other than boots and shoes	
      civ_occupation == 500 ~ 500, #Skilled occupations in manufacture of miscellaneous electrical equipment, n.e.c.	 
      civ_occupation == 439 ~ 439, #Skilled occupations in manufacture of miscellaneous finished lumber products, n.e.c.	
      civ_occupation == 441 ~ 441, #Skilled occupations in manufacture of paper and pulp	
      civ_occupation == 509 ~ 509, #Skilled occupations in manufacture of professional and scientific apparatus, n.e.c.	
      civ_occupation == 498 ~ 498, #Skilled occupations in manufacture of radios and phonographs	
      civ_occupation == 419 ~ 419, #Skilled occupations in manufacture of textiles, n.e.c.	
      civ_occupation == 412 ~ 412, #Skilled occupations in manufacture of tobacco products	
      civ_occupation == 488 ~ 488, #Skilled occupations in mechanical treatment of metals (rolling, stamping, forging, pressing, etc.), n.e.c.	
      civ_occupation == 449 ~ 449, #Skilled occupations in printing and publishing, n.e.c.	
      civ_occupation == 406 ~ 406, #Skilled occupations in processing of dairy products	
      civ_occupation == 470 ~ 470, #Skilled occupations in production of asbestos products, abrasives, and polishing products	
      civ_occupation == 402 ~ 402, #Skilled occupations in production of bakery products, n.e.c.	    
      civ_occupation == 403 ~ 403, #Skilled occupations in production of beverages	
      civ_occupation == 453 ~ 453, #Skilled occupations in production of chemical products, n.e.c.	
      civ_occupation == 466 ~ 466, #Skilled occupations in production of clay products	
      civ_occupation == 405 ~ 405, #Skilled occupations in production of confections	
      civ_occupation == 492 ~ 492, #Skilled occupations in production of ferrous and nonferrous metals, n.e.c.	
      civ_occupation == 465 ~ 465, #Skilled occupations in production of glass and glass products	
      civ_occupation == 408 ~ 408, #Skilled occupations in production of grain-mill products, n.e.c.	
      civ_occupation == 452 ~ 452, #Skilled occupations in production of industrial chemicals	
      civ_occupation == 410 ~ 410, #Skilled occupations in production of miscellaneous food products   
      civ_occupation == 450 ~ 450, #Skilled occupations in production of paint and varnish	
      civ_occupation == 457 ~ 457, #Skilled occupations in production of rubber goods	
      civ_occupation == 451 ~ 451, #Skilled occupations in production of synthetic fibers and processing of chemicals and other materials, n.e.c.	
      civ_occupation == 455 ~ 455, #Skilled occupations in refining of petroleum	
      civ_occupation == 409 ~ 409, #Skilled occupations in slaughtering and in preparation of meat products	
      civ_occupation == 469 ~ 469, #Skilled occupations in stoneworking, n.e.c.	
      civ_occupation == 513 ~ 513, #Skilled occupations in the manufacture of miscellaneous products	
      civ_occupation == 559 ~ 559, #Skilled occupations in trades and services, n.e.c.	
      civ_occupation == 490 ~ 490, #Skilled ore dressing occupations	  
      civ_occupation == 527 ~ 527, #Skilled painters, construction and maintenance	
      civ_occupation == 516 ~ 516, #Skilled painters, except construction and maintenance	
      civ_occupation == 517 ~ 517, #Skilled pattern and model makers, except paper	
      civ_occupation == 586 ~ 586, #Skilled photographic process occupations	
      civ_occupation == 434 ~ 434, #Skilled planing mill occupations, n.e.c.	
      civ_occupation == 561 ~ 561, #Skilled public service occupations, n.e.c.	
      civ_occupation == 431 ~ 431, #Skilled sawmill occupations, n.e.c.	
      civ_occupation == 544 ~ 544, #Skilled switchmen, railroad	
      civ_occupation == 537 ~ 537, #Skilled teamsters	
      civ_occupation == 584 ~ 584, #Skilled tool sharpeners and dressers	
      civ_occupation == 549 ~ 549, #Skilled transportation occupations, n.e.c.	
      civ_occupation == 588 ~ 588, #Skilled warehousing, storekeeping, handling, loading, unloading, and related occupations, n.e.c.	
      civ_occupation == 485 ~ 485, #Skilled welders and flame cutters	
      civ_occupation == 027 ~ 027, #Social and welfare workers	
      civ_occupation == 268 ~ 268, #Soldiers, sailors, marines, and coast guards, n.e.c.	
      civ_occupation == 388 ~ 388, #Sponge and seaweed gathers	
      civ_occupation == 343 ~ 343, #Stablemen	
      civ_occupation == 136 ~ 136, #Statistical clerks and compilers	
      civ_occupation == 028 ~ 028, #Statisticians	
      civ_occupation == 137 ~ 137, #Stenographers and typists	
      civ_occupation == 138 ~ 138, #Stock clerks	
      civ_occupation == 468 ~ 468, #Stonecutters	
      civ_occupation == 484 ~ 484, #Structural-and ornamental-metal workers	
      civ_occupation == 064 ~ 064, #Surveyors	
      civ_occupation == 426 ~ 426, #Tailors and tailoresses	
      civ_occupation == 031 ~ 031, #Teachers (secondary school) and principals	
      civ_occupation == 032 ~ 032, #Teachers and instructors, n.e.c.	
      civ_occupation == 030 ~ 030, #Teachers, primary school and kindergarten	
      civ_occupation == 135 ~ 135, #Technical Clerks, n.e.c.	
      civ_occupation == 348 ~ 348, #Technical agricultural occupations, n.e.c.	
      civ_occupation == 066 ~ 066, #Technicians, except laboratory	
      civ_occupation == 124 ~ 124, #Telegraph messengers	
      civ_occupation == 141 ~ 141, #Telegraph operators	
      civ_occupation == 142 ~ 142, #Telephone operators	
      civ_occupation == 144 ~ 144, #Ticket, station, and express agents, transportation	
      civ_occupation == 480 ~ 480, #Tinsmiths, coppersmiths, and sheet metal workers	
      civ_occupation == 476 ~ 476, #Toolmakers and die sinkers and setters	
      civ_occupation == 033 ~ 033, #Trained nurses	
      civ_occupation == 309 ~ 309, #Truck farmers	   
      civ_occupation == 821 ~ 821, #Unskilled Furriers and occupations in fabrication of fur good, n.e.c.	
      civ_occupation == 956 ~ 956, #Unskilled amusement, recreation, and motion picture occupations, n.e.c.	
      civ_occupation == 883 ~ 883, #Unskilled boilermakers	
      civ_occupation == 987 ~ 987, #Unskilled chainmen, rodmen, and axmen, surveying	
      civ_occupation == 932 ~ 932, #Unskilled construction occupations, n.e.c.	
      civ_occupation == 838 ~ 838, #Unskilled cooperage occupations, n.e.c.	
      civ_occupation == 877 ~ 877, #Unskilled filers, grinders, buffers, and polishers (metal)	
      civ_occupation == 882 ~ 882, #Unskilled foundry occupations, n.e.c.	
      civ_occupation == 985 ~ 985, #Unskilled garage laborers and car washers and greasers	    
      civ_occupation == 833 ~ 833, #Unskilled general woodworking occupations, n.e.c.	
      civ_occupation == 977 ~ 977, #Unskilled glaziers	
      civ_occupation == 887 ~ 887, #Unskilled heat treaters, annealers, and temperers	
      civ_occupation == 947 ~ 947, #Unskilled longshoremen and stevedores	
      civ_occupation == 830 ~ 830, #Unskilled lumbermen, raftsmen, and woodchoppers	
      civ_occupation == 878 ~ 878, #Unskilled machine shop and related occupations, n.e.c.	
      civ_occupation == 983 ~ 983, #Unskilled mechanics and repairmen, n.e.c.	
      civ_occupation == 989 ~ 989, #Unskilled miscellaneous occupations, n.e.c.	
      civ_occupation == 681 ~ 681, #Unskilled molders	
      civ_occupation == 963 ~ 963, #Unskilled nonprocess occupations in manufacturing, n.e.c.	
      civ_occupation == 964 ~ 964, #Unskilled nonprocess occupations in manufacturing, n.e.c.	
      civ_occupation == 965 ~ 965, #Unskilled nonprocess occupations in manufacturing, n.e.c.	
      civ_occupation == 903 ~ 903, #Unskilled occupations in building of aircraft, n.e.c.	
      civ_occupation == 905 ~ 905, #Unskilled occupations in building transportation equipment (except automobiles and aircraft), n.e.c.	
      civ_occupation == 804 ~ 804, #Unskilled occupations in canning and preserving of foods	
      civ_occupation == 874 ~ 874, #Unskilled occupations in electroplating, galvanizing, and related processes	
      civ_occupation == 922 ~ 922, #Unskilled occupations in extraction of minerals, n.e.c.	
      civ_occupation == 894 ~ 894, #Unskilled occupations in fabrication of metal products, n.e.c.	
      civ_occupation == 893 ~ 893,#Unskilled occupations in fabrication of metal products, n.e.c.
      civ_occupation == 827 ~ 827,  #Unskilled occupations in fabrication of textile products, n.e.c. 	
      civ_occupation == 954 ~ 954, #Unskilled occupations in furnishing utilities, n.e.c.	
      civ_occupation == 957 ~ 957, #Unskilled occupations in laundering, cleaning, dyeing, and pressing apparel and other articles	
      civ_occupation == 902 ~ 902, #Unskilled occupations in manufacture of automobiles, n.e.c.	
      civ_occupation == 861 ~ 861, #Unskilled occupations in manufacture of boots and shoes	
      civ_occupation == 872 ~ 872, #Unskilled occupations in manufacture of clocks, watches, jewelry, and articles of precious metals	
      civ_occupation == 899 ~ 899, #Unskilled occupations in manufacture of electrical machinery and accessories, n.e.c.	
      civ_occupation == 910 ~ 910, #Unskilled occupations in manufacture of fabricated plastic products	
      civ_occupation == 836 ~ 836, #Unskilled occupations in manufacture of furniture, n.e.c.	
      civ_occupation == 824 ~ 824, #Unskilled occupations in manufacture of hats and caps, n.e.c.	
      civ_occupation == 814 ~ 814, #Unskilled occupations in manufacture of knit goods	
      civ_occupation == 859 ~ 859, #Unskilled occupations in manufacture of leather	
      civ_occupation == 862 ~ 862, #Unskilled occupations in manufacture of leather products other than boots and shoes	
      civ_occupation == 900 ~ 900, #Unskilled occupations in manufacture of miscellaneous electrical equipment, n.e.c.	
      civ_occupation == 839 ~ 839, #Unskilled occupations in manufacture of miscellaneous finished lumber products, n.e.c.	
      civ_occupation == 841 ~ 841, #Unskilled occupations in manufacture of paper and pulp	
      civ_occupation == 842 ~ 842, #Unskilled occupations in manufacture of paper goods	
      civ_occupation == 909 ~ 909, #Unskilled occupations in manufacture of professional and scientific apparatus, n.e.c.	
      civ_occupation == 898 ~ 898, #Unskilled occupations in manufacture of radios and phonographs	   
      civ_occupation == 819 ~ 819, #Unskilled occupations in manufacture of textiles, n.e.c.	
      civ_occupation == 812 ~ 812, #Unskilled occupations in manufacture of tobacco products	
      civ_occupation == 849 ~ 849, #Unskilled occupations in printing and publishing, n.e.c.	
      civ_occupation == 806 ~ 806, #Unskilled occupations in processing of dairy products	
      civ_occupation == 870 ~ 870, #Unskilled occupations in production of asbestos products, abrasives, and polishing products	
      civ_occupation == 802 ~ 802, #Unskilled occupations in production of bakery products, n.e.c.	
      civ_occupation == 803 ~ 803, #Unskilled occupations in production of beverages	
      civ_occupation == 867 ~ 867, #Unskilled occupations in production of cement, concrete, gypsum, and plaster product	
      civ_occupation == 853 ~ 853, #Unskilled occupations in production of chemical products, n.e.c.
      civ_occupation == 866 ~ 866, #Unskilled occupations in production of clay products	
      civ_occupation == 805 ~ 805, #Unskilled occupations in production of confections	
      civ_occupation == 892 ~ 892, #Unskilled occupations in production of ferrous and nonferrous metals, n.e.c.	
      civ_occupation == 865 ~ 865, #Unskilled occupations in production of glass and glass products	
      civ_occupation == 808 ~ 808, #Unskilled occupations in production of grain-mill products, n.e.c.
      civ_occupation == 852 ~ 852, #Unskilled occupations in production of industrial chemicals	
      civ_occupation == 810 ~ 810, #Unskilled occupations in production of miscellaneous food products
      civ_occupation == 856 ~ 856, #Unskilled occupations in production of miscellaneous petroleum and coal products	
      civ_occupation == 850 ~ 850, #Unskilled occupations in production of paint and varnish	
      civ_occupation == 920 ~ 920, #Unskilled occupations in production of petroleum	
      civ_occupation == 851 ~ 851, #Unskilled occupations in production of rayon and allied products	
      civ_occupation == 857 ~ 857, #Unskilled occupations in production of rubber goods	
      civ_occupation == 855 ~ 855, #Unskilled occupations in refining of petroleum	
      civ_occupation == 809 ~ 809, #Unskilled occupations in slaughtering and in preparation of meat products	
      civ_occupation == 869 ~ 869, #Unskilled occupations in stoneworking, n.e.c.	
      civ_occupation == 913 ~ 913, #Unskilled occupations in the manufacture of miscellaneous products	
      civ_occupation == 959 ~ 959, #Unskilled occupations in trades and services, n.e.c.	
      civ_occupation == 971 ~ 971, #Unskilled oilers of machinery	
      civ_occupation == 916 ~ 916, #Unskilled painters, except construction and maintenance	
      civ_occupation == 986 ~ 986, #Unskilled photographic process occupations	   
      civ_occupation == 834 ~ 834, #Unskilled planing mill occupations, n.e.c.	
      civ_occupation == 961 ~ 961, #Unskilled public service occupations, n.e.c.	
      civ_occupation == 935 ~ 935, #Unskilled routemen	
      civ_occupation == 948 ~ 948, #Unskilled sailors and deckhands, except U.S. Navy	
      civ_occupation == 831 ~ 831, #Unskilled sawmill occupations, n.e.c.	
      civ_occupation == 884 ~ 884, #Unskilled structural- and ornamental-metal workers	
      civ_occupation == 949 ~ 949, #Unskilled transportation occupations, n.e.c.	
      civ_occupation == 248 ~ 248, #Ushers	
      civ_occupation == 034 ~ 034, #Veterinarians	
      civ_occupation == 227 ~ 227, #Waiters and waitresses, except private family	
      civ_occupation == 415 ~ 415, #Weavers, textile	  
      civ_occupation == 145 ~ 145, #Weighers
      civ_occupation == 073 ~ 073, #Wholesale managers
      TRUE ~ NA_real_     ## this recodes anything remaining to NA (this is better than blank)
    ))
  
  ## return data.frame   
  return(df)
}
```
#Recode civ_occupation 
```{r}
civ_occupation_recode <- recode_civ_occupation_enlistment(df = data_combined) %>% 
  select(civ_occupation, civ_occupation_recode)
```

#add civ_occupation_recode to data_combined
```{r}
data_combined <- cbind(data_combined, civ_occupation_recode$civ_occupation_recode, res_state_recode$state_recode)

```

#save dataset as temp7
```{r}
write_csv(data_combined, paste0(out_path, "/temp8.csv"))
rm(list = ls())
```
