---
title: "9-final-clean-enlistment"
output: html_document
date: "2023-03-02"
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)   # %>%, group_by, tally, print
library(ipumsr)  # read_ipums_ddi, ipums_val_labels
library(readr)   # read_csv, write_csv
library(stringr) # str_trim, str_split
```

#update path
```{r}
path_to_temp_data   <-  "/data/censoc/workspace/enlistment_records/temp8.csv"
out_path <- "/data/censoc/workspace/enlistment_records/"
```

```{r}
data_combined <- read_csv(path_to_temp_data, 
                          col_types = cols(
                            empty_field = col_character(),
                            term_or_enlistment = col_character(),
                            longevity = col_character(),
                            education = col_character(),
                            marital_status = col_character(),
                            component = col_character(),
                            educ_spec = col_character(),
                            defer_date_mmyy = col_character(),
                            mname_clean = col_character(),
                            sex = col_integer(),
                            sex_r = col_integer(),
                            fname_std = col_character()
                            )
                          )
```

#Create final df using the subset function and rename columns
```{r}
colnames(data_combined)
```

```{r}
enlistment_records_final_v1 <- subset(data_combined, select = c( "serial_number",  "yob_precise", "fname_clean_std" , "mname_clean" ,"lname_clean", "sex_r", "date_enlistment_recode", "nativity_recode$nativity_recode" , "residence_county", "res_state_recode$state_recode", "place_of_enlistment","education_recode$education_recode","grade_recode$grade_code_recode",  "branch_recode$branch_code_recode", "term_or_enlistment_recode$term_or_enlistment_recode", "race_recode$race_recode", "citizenship_recode$citizenship_recode", "civ_occupation_recode$civ_occupation_recode" ,"marital_status_recode$marital_status_recode", "height_recode", "weight_before_1943","weight_or_AGCT", "component_recode$component_recode","source_recode$source_recode"))

```
#test df by looking at the first 200 rows
```{r}
head(enlistment_records_final_v1, 200)
```
#rename columns
```{r}
enlistment_records_final <- enlistment_records_final_v1 %>% 
        rename(  
               "fname" = "fname_clean_std",
               "mname" = "mname_clean",
                "lname" = "lname_clean",
               "sex" = "sex_r",
               "residence_state"="res_state_recode$state_recode",
               "byear" = "yob_precise",
               "bpl"="nativity_recode$nativity_recode"  ,
               "date_of_enlistment" = "date_enlistment_recode",
               "source" = "source_recode$source_recode" ,
               "grade_code" = "grade_recode$grade_code_recode" , 
              "term_of_enlistment" = "term_or_enlistment_recode$term_or_enlistment_recode" , 
              "branch_code" = "branch_recode$branch_code_recode" ,
              "component" = "component_recode$component_recode" , 
               "race" = "race_recode$race_recode", 
               "citizenship" = "citizenship_recode$citizenship_recode", 
               "education" = "education_recode$education_recode" ,
               "marital_status" = "marital_status_recode$marital_status_recode" , 
               "height" = "height_recode",
               "civilian_occupation" = "civ_occupation_recode$civ_occupation_recode" )
```

```{r}
head(enlistment_records_final, 200)
```


# remove rows that contain no actual data 
About 160,000 rows contain the string "ONE OR MORE CARDS WERE UNREADABLE AT THIS LOCATION",
indicating a gap in the data rather than an actual data record.
9,200,232 rows --> 9,039,840 rows
```{r}
enlistment_records_final <- enlistment_records_final %>%
  filter(serial_number != "ONE OR M")
```



#save final dataset
```{r}
write_csv(enlistment_records_final, paste0(out_path, "/finalenlistment.csv"))
rm(list = ls())
```

